# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81dc38a6886e9463901268bdde6d9825"
application_url = "https://shop-x-restrict-y.onrender.com"
embedded = true
name = "shop-x-restrict-y"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_validations,write_metaobjects,write_products,write_validations,read_themes"

[auth]
redirect_urls = [ "https://shop-x-restrict-y.onrender.com/auth/callback" ,"https://shop-x-restrict-y.onrender.com/auth/shopify/callback", "https://shop-x-restrict-y.onrender.com/api/auth/callback" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
